package localstore

import (
	"bytes"
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"time"

	"github.com/H4RL33/wormhole/internal/types"
	projectstate "github.com/H4RL33/wormhole/internal/types/projectstate"
)

// WorkspaceTransitionReceiptInsert is the neutral durable idempotency record
// written by a workspace transition in the same immediate transaction.
type WorkspaceTransitionReceiptInsert struct {
	RequestID     string
	Action        string
	RequestDigest projectstate.Digest
	Actor         types.ActorEnvelope
	ResultJSON    json.RawMessage
	Outcome       string
}

// WorkspaceTransitionReceiptRecord is an immutable persisted transition
// receipt. CreatedAt is generated by SQLite and normalized to UTC on read.
type WorkspaceTransitionReceiptRecord struct {
	WorkspaceTransitionReceiptInsert
	CreatedAt time.Time
}

// TransitionReceipt reads one immutable receipt from the exact workspace on a
// repository connection. A valid missing key returns nil, nil.
func (r *WorkspaceRepo) TransitionReceipt(ctx context.Context, scope types.WorkspaceScope, requestID string) (*WorkspaceTransitionReceiptRecord, error) {
	if r == nil || r.db == nil || !validWorkspaceScope(scope) {
		return nil, ErrNotFound
	}
	return readWorkspaceTransitionReceipt(ctx, r.db, scope, requestID)
}

// TransitionReceipt reads one immutable receipt from this transaction's exact
// workspace. A valid missing key returns nil, nil.
func (tx *WorkspaceMutationTx) TransitionReceipt(ctx context.Context, requestID string) (*WorkspaceTransitionReceiptRecord, error) {
	if tx == nil || tx.conn == nil || !validWorkspaceScope(tx.scope) {
		return nil, ErrNotFound
	}
	return readWorkspaceTransitionReceipt(ctx, tx.conn, tx.scope, requestID)
}

// InsertTransitionReceipt appends exactly one canonical immutable receipt to
// this transaction's exact workspace.
func (tx *WorkspaceMutationTx) InsertTransitionReceipt(ctx context.Context, receipt WorkspaceTransitionReceiptInsert) error {
	if tx == nil || tx.conn == nil || !validWorkspaceScope(tx.scope) {
		return ErrNotFound
	}
	actorJSON, resultJSON, err := validateWorkspaceTransitionReceiptInsert(receipt)
	if err != nil {
		return err
	}
	existing, err := tx.TransitionReceipt(ctx, receipt.RequestID)
	if err != nil {
		return fmt.Errorf("localstore: preflight workspace transition receipt insert: %w", err)
	}
	if existing != nil {
		return fmt.Errorf("localstore: workspace transition receipt immutable key collision")
	}
	result, err := tx.conn.ExecContext(ctx, `
		INSERT INTO workspace_transition_receipts
		(project_id, workspace_id, request_id, action, request_digest, actor_json, result_json, outcome)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?)
	`, tx.scope.ProjectID, tx.scope.WorkspaceID, receipt.RequestID, receipt.Action,
		string(receipt.RequestDigest), string(actorJSON), string(resultJSON), receipt.Outcome)
	if err != nil {
		return fmt.Errorf("localstore: insert workspace transition receipt: %w", err)
	}
	inserted, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("localstore: inspect workspace transition receipt insert: %w", err)
	}
	if inserted != 1 {
		return fmt.Errorf("localstore: workspace transition receipt insert affected %d rows", inserted)
	}
	return nil
}

type workspaceTransitionReceiptQueryer interface {
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

func readWorkspaceTransitionReceipt(ctx context.Context, queryer workspaceTransitionReceiptQueryer, scope types.WorkspaceScope, requestID string) (*WorkspaceTransitionReceiptRecord, error) {
	if !types.CanonicalUUID(requestID) {
		return nil, fmt.Errorf("localstore: invalid workspace transition request ID")
	}
	record, err := scanOptionalWorkspaceTransitionReceipt(queryer.QueryRowContext(ctx, `
		SELECT binding.project_id, binding.workspace_id,
		       COUNT(receipt.rowid) OVER (),
		       receipt.project_id, receipt.workspace_id, receipt.request_id,
		       receipt.action, receipt.request_digest, receipt.actor_json,
		       receipt.result_json, receipt.outcome, receipt.created_at,
		       NULLIF(typeof(receipt.project_id),'null'), NULLIF(typeof(receipt.workspace_id),'null'),
		       NULLIF(typeof(receipt.request_id),'null'), NULLIF(typeof(receipt.action),'null'),
		       NULLIF(typeof(receipt.request_digest),'null'), NULLIF(typeof(receipt.actor_json),'null'),
		       NULLIF(typeof(receipt.result_json),'null'), NULLIF(typeof(receipt.outcome),'null'),
		       NULLIF(typeof(receipt.created_at),'null')
		FROM workspace_bindings AS binding
		LEFT JOIN workspace_transition_receipts AS receipt
		  ON CAST(receipt.project_id AS TEXT)=binding.project_id
		 AND CAST(receipt.workspace_id AS TEXT)=binding.workspace_id
		 AND CAST(receipt.request_id AS TEXT)=?
		WHERE binding.project_id=? AND binding.workspace_id=?
	`, requestID, scope.ProjectID, scope.WorkspaceID), scope, requestID)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("localstore: decode workspace transition receipt: %w", err)
	}
	return record, nil
}

func scanOptionalWorkspaceTransitionReceipt(
	scanner interface{ Scan(...any) error },
	expectedScope types.WorkspaceScope,
	expectedRequestID string,
) (*WorkspaceTransitionReceiptRecord, error) {
	var (
		scope                                      types.WorkspaceScope
		matchingReceiptCount                       int64
		projectID, workspaceID, requestID          sql.NullString
		action, digest, actorJSON, resultJSON      sql.NullString
		outcome                                    sql.NullString
		createdAt                                  sql.NullTime
		projectClass, workspaceClass, requestClass sql.NullString
		actionClass, digestClass, actorClass       sql.NullString
		resultClass, outcomeClass, timeClass       sql.NullString
	)
	if err := scanner.Scan(
		&scope.ProjectID, &scope.WorkspaceID, &matchingReceiptCount,
		&projectID, &workspaceID, &requestID, &action, &digest,
		&actorJSON, &resultJSON, &outcome, &createdAt,
		&projectClass, &workspaceClass, &requestClass, &actionClass, &digestClass,
		&actorClass, &resultClass, &outcomeClass, &timeClass,
	); err != nil {
		return nil, err
	}
	if scope != expectedScope || !validWorkspaceScope(scope) {
		return nil, fmt.Errorf("workspace transition receipt scope differs from request")
	}
	if matchingReceiptCount < 0 || matchingReceiptCount > 1 {
		return nil, fmt.Errorf("ambiguous persisted workspace transition receipt key")
	}
	classes := []sql.NullString{
		projectClass, workspaceClass, requestClass, actionClass, digestClass,
		actorClass, resultClass, outcomeClass, timeClass,
	}
	if !requestID.Valid {
		if matchingReceiptCount != 0 {
			return nil, fmt.Errorf("incomplete persisted transition receipt key")
		}
		if projectID.Valid || workspaceID.Valid || action.Valid || digest.Valid || actorJSON.Valid ||
			resultJSON.Valid || outcome.Valid || createdAt.Valid {
			return nil, fmt.Errorf("incomplete persisted transition receipt")
		}
		for _, class := range classes {
			if class.Valid {
				return nil, fmt.Errorf("invalid absent workspace transition receipt storage class")
			}
		}
		return nil, nil
	}
	if matchingReceiptCount != 1 {
		return nil, fmt.Errorf("incomplete persisted transition receipt key")
	}
	if !projectID.Valid || !workspaceID.Valid || !action.Valid || !digest.Valid || !actorJSON.Valid ||
		!resultJSON.Valid || !outcome.Valid || !createdAt.Valid {
		return nil, fmt.Errorf("incomplete persisted transition receipt")
	}
	for _, class := range classes {
		if !class.Valid || class.String != "text" {
			return nil, fmt.Errorf("invalid persisted workspace transition receipt storage class")
		}
	}
	if projectID.String != expectedScope.ProjectID || workspaceID.String != string(expectedScope.WorkspaceID) || requestID.String != expectedRequestID {
		return nil, fmt.Errorf("persisted workspace transition receipt key mismatch")
	}
	record := WorkspaceTransitionReceiptRecord{
		WorkspaceTransitionReceiptInsert: WorkspaceTransitionReceiptInsert{
			RequestID:     requestID.String,
			Action:        action.String,
			RequestDigest: projectstate.Digest(digest.String),
			Outcome:       outcome.String,
		},
		CreatedAt: createdAt.Time,
	}
	if !types.CanonicalUUID(record.RequestID) {
		return nil, fmt.Errorf("invalid persisted request ID")
	}
	switch record.Action {
	case "stash", "restore", "discard":
	default:
		return nil, fmt.Errorf("invalid persisted transition action %q", record.Action)
	}
	if !validWorkspaceTransitionDigest(record.RequestDigest) {
		return nil, fmt.Errorf("invalid persisted transition request digest")
	}
	actor, err := decodeCanonicalTransitionActor([]byte(actorJSON.String))
	if err != nil {
		return nil, err
	}
	record.Actor = actor
	resultBytes := []byte(resultJSON.String)
	canonicalResult, err := canonicalTransitionResult(resultBytes)
	if err != nil || !bytes.Equal(canonicalResult, resultBytes) {
		return nil, fmt.Errorf("invalid persisted transition result JSON")
	}
	record.ResultJSON = bytes.Clone(resultBytes)
	switch record.Outcome {
	case "clean", "conflicted":
	default:
		return nil, fmt.Errorf("invalid persisted transition outcome %q", record.Outcome)
	}
	if !validUTCTimestamp(record.CreatedAt) {
		return nil, fmt.Errorf("invalid persisted transition timestamp")
	}
	record.CreatedAt = record.CreatedAt.UTC()
	return &record, nil
}

func validateWorkspaceTransitionReceiptInsert(receipt WorkspaceTransitionReceiptInsert) ([]byte, []byte, error) {
	if !types.CanonicalUUID(receipt.RequestID) {
		return nil, nil, fmt.Errorf("localstore: invalid workspace transition request ID")
	}
	switch receipt.Action {
	case "stash", "restore", "discard":
	default:
		return nil, nil, fmt.Errorf("localstore: invalid workspace transition action %q", receipt.Action)
	}
	if !validWorkspaceTransitionDigest(receipt.RequestDigest) {
		return nil, nil, fmt.Errorf("localstore: invalid workspace transition request digest")
	}
	if err := receipt.Actor.ValidateHistorical(); err != nil {
		return nil, nil, fmt.Errorf("localstore: invalid workspace transition actor: %w", err)
	}
	actorJSON, err := projectstate.CanonicalJSON(receipt.Actor)
	if err != nil {
		return nil, nil, fmt.Errorf("localstore: encode workspace transition actor: %w", err)
	}
	resultJSON, err := canonicalTransitionResult(receipt.ResultJSON)
	if err != nil || !bytes.Equal(resultJSON, receipt.ResultJSON) {
		return nil, nil, fmt.Errorf("localstore: workspace transition result is not one canonical JSON value")
	}
	switch receipt.Outcome {
	case "clean", "conflicted":
	default:
		return nil, nil, fmt.Errorf("localstore: invalid workspace transition outcome %q", receipt.Outcome)
	}
	return actorJSON, bytes.Clone(resultJSON), nil
}

func decodeCanonicalTransitionActor(data []byte) (types.ActorEnvelope, error) {
	var actor types.ActorEnvelope
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&actor); err != nil {
		return types.ActorEnvelope{}, fmt.Errorf("invalid persisted transition actor JSON: %w", err)
	}
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err == nil {
			return types.ActorEnvelope{}, fmt.Errorf("invalid persisted transition actor JSON: multiple values")
		}
		return types.ActorEnvelope{}, fmt.Errorf("invalid persisted transition actor JSON: %w", err)
	}
	canonical, err := projectstate.CanonicalJSON(actor)
	if err != nil || !bytes.Equal(canonical, data) {
		return types.ActorEnvelope{}, fmt.Errorf("persisted transition actor JSON is not canonical")
	}
	if err := actor.ValidateHistorical(); err != nil {
		return types.ActorEnvelope{}, fmt.Errorf("invalid persisted transition actor: %w", err)
	}
	return actor, nil
}

func canonicalTransitionResult(data json.RawMessage) ([]byte, error) {
	var compact bytes.Buffer
	if err := json.Compact(&compact, data); err != nil {
		return nil, err
	}
	compact.WriteByte('\n')
	if !bytes.Equal(compact.Bytes(), data) {
		return nil, fmt.Errorf("transition result is not compact JSON with one trailing newline")
	}
	return bytes.Clone(data), nil
}

func validWorkspaceTransitionDigest(digest projectstate.Digest) bool {
	value := string(digest)
	if len(value) != len("sha256:")+64 || value[:len("sha256:")] != "sha256:" {
		return false
	}
	for _, char := range value[len("sha256:"):] {
		if !((char >= '0' && char <= '9') || (char >= 'a' && char <= 'f')) {
			return false
		}
	}
	return true
}
