package localstore

import (
	"bytes"
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"time"

	"github.com/H4RL33/wormhole/internal/types"
	projectstate "github.com/H4RL33/wormhole/internal/types/projectstate"
)

// WorkspaceTransitionReceiptInsert is the neutral durable idempotency record
// written by a workspace transition in the same immediate transaction.
type WorkspaceTransitionReceiptInsert struct {
	RequestID     string
	Action        string
	RequestDigest projectstate.Digest
	Actor         types.ActorEnvelope
	ResultJSON    json.RawMessage
	Outcome       string
}

// WorkspaceTransitionReceiptRecord is an immutable persisted transition
// receipt. CreatedAt is generated by SQLite and normalized to UTC on read.
type WorkspaceTransitionReceiptRecord struct {
	WorkspaceTransitionReceiptInsert
	CreatedAt time.Time
}

// TransitionReceipt reads one immutable receipt from the exact workspace on a
// repository connection. A valid missing key returns nil, nil.
func (r *WorkspaceRepo) TransitionReceipt(ctx context.Context, scope types.WorkspaceScope, requestID string) (*WorkspaceTransitionReceiptRecord, error) {
	if r == nil || r.db == nil || !validWorkspaceScope(scope) {
		return nil, ErrNotFound
	}
	return readWorkspaceTransitionReceipt(ctx, r.db, scope, requestID)
}

// TransitionReceipt reads one immutable receipt from this transaction's exact
// workspace. A valid missing key returns nil, nil.
func (tx *WorkspaceMutationTx) TransitionReceipt(ctx context.Context, requestID string) (*WorkspaceTransitionReceiptRecord, error) {
	if tx == nil || tx.conn == nil || !validWorkspaceScope(tx.scope) {
		return nil, ErrNotFound
	}
	return readWorkspaceTransitionReceipt(ctx, tx.conn, tx.scope, requestID)
}

// InsertTransitionReceipt appends exactly one canonical immutable receipt to
// this transaction's exact workspace.
func (tx *WorkspaceMutationTx) InsertTransitionReceipt(ctx context.Context, receipt WorkspaceTransitionReceiptInsert) error {
	if tx == nil || tx.conn == nil || !validWorkspaceScope(tx.scope) {
		return ErrNotFound
	}
	actorJSON, resultJSON, err := validateWorkspaceTransitionReceiptInsert(receipt)
	if err != nil {
		return err
	}
	result, err := tx.conn.ExecContext(ctx, `
		INSERT INTO workspace_transition_receipts
		(project_id, workspace_id, request_id, action, request_digest, actor_json, result_json, outcome)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?)
	`, tx.scope.ProjectID, tx.scope.WorkspaceID, receipt.RequestID, receipt.Action,
		string(receipt.RequestDigest), string(actorJSON), string(resultJSON), receipt.Outcome)
	if err != nil {
		return fmt.Errorf("localstore: insert workspace transition receipt: %w", err)
	}
	inserted, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("localstore: inspect workspace transition receipt insert: %w", err)
	}
	if inserted != 1 {
		return fmt.Errorf("localstore: workspace transition receipt insert affected %d rows", inserted)
	}
	return nil
}

type workspaceTransitionReceiptQueryer interface {
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

func readWorkspaceTransitionReceipt(ctx context.Context, queryer workspaceTransitionReceiptQueryer, scope types.WorkspaceScope, requestID string) (*WorkspaceTransitionReceiptRecord, error) {
	if !types.CanonicalUUID(requestID) {
		return nil, fmt.Errorf("localstore: invalid workspace transition request ID")
	}
	record, rowScope, err := scanOptionalWorkspaceTransitionReceipt(queryer.QueryRowContext(ctx, `
		SELECT binding.project_id, binding.workspace_id,
		       receipt.request_id, receipt.action, receipt.request_digest,
		       receipt.actor_json, receipt.result_json, receipt.outcome, receipt.created_at
		FROM workspace_bindings AS binding
		LEFT JOIN workspace_transition_receipts AS receipt
		  ON receipt.project_id=binding.project_id
		 AND receipt.workspace_id=binding.workspace_id
		 AND receipt.request_id=?
		WHERE binding.project_id=? AND binding.workspace_id=?
	`, requestID, scope.ProjectID, scope.WorkspaceID))
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("localstore: decode workspace transition receipt: %w", err)
	}
	if rowScope != scope {
		return nil, fmt.Errorf("localstore: workspace transition receipt key mismatch")
	}
	if record == nil {
		return nil, nil
	}
	if record.RequestID != requestID {
		return nil, fmt.Errorf("localstore: workspace transition receipt request mismatch")
	}
	return record, nil
}

func scanOptionalWorkspaceTransitionReceipt(scanner interface{ Scan(...any) error }) (*WorkspaceTransitionReceiptRecord, types.WorkspaceScope, error) {
	var scope types.WorkspaceScope
	var requestID, action, digest, actorJSON, resultJSON, outcome sql.NullString
	var createdAt sql.NullTime
	if err := scanner.Scan(
		&scope.ProjectID, &scope.WorkspaceID, &requestID, &action, &digest,
		&actorJSON, &resultJSON, &outcome, &createdAt,
	); err != nil {
		return nil, types.WorkspaceScope{}, err
	}
	if !validWorkspaceScope(scope) {
		return nil, types.WorkspaceScope{}, fmt.Errorf("invalid persisted workspace scope")
	}
	if !requestID.Valid {
		if action.Valid || digest.Valid || actorJSON.Valid || resultJSON.Valid || outcome.Valid || createdAt.Valid {
			return nil, types.WorkspaceScope{}, fmt.Errorf("incomplete persisted transition receipt")
		}
		return nil, scope, nil
	}
	if !action.Valid || !digest.Valid || !actorJSON.Valid || !resultJSON.Valid || !outcome.Valid || !createdAt.Valid {
		return nil, types.WorkspaceScope{}, fmt.Errorf("incomplete persisted transition receipt")
	}
	record := WorkspaceTransitionReceiptRecord{
		WorkspaceTransitionReceiptInsert: WorkspaceTransitionReceiptInsert{
			RequestID:     requestID.String,
			Action:        action.String,
			RequestDigest: projectstate.Digest(digest.String),
			Outcome:       outcome.String,
		},
		CreatedAt: createdAt.Time,
	}
	if !types.CanonicalUUID(record.RequestID) {
		return nil, types.WorkspaceScope{}, fmt.Errorf("invalid persisted request ID")
	}
	switch record.Action {
	case "stash", "restore", "discard":
	default:
		return nil, types.WorkspaceScope{}, fmt.Errorf("invalid persisted transition action %q", record.Action)
	}
	if !validWorkspaceTransitionDigest(record.RequestDigest) {
		return nil, types.WorkspaceScope{}, fmt.Errorf("invalid persisted transition request digest")
	}
	actor, err := decodeCanonicalTransitionActor([]byte(actorJSON.String))
	if err != nil {
		return nil, types.WorkspaceScope{}, err
	}
	record.Actor = actor
	resultBytes := []byte(resultJSON.String)
	canonicalResult, err := canonicalTransitionResult(resultBytes)
	if err != nil || !bytes.Equal(canonicalResult, resultBytes) {
		return nil, types.WorkspaceScope{}, fmt.Errorf("invalid persisted transition result JSON")
	}
	record.ResultJSON = bytes.Clone(resultBytes)
	switch record.Outcome {
	case "clean", "conflicted":
	default:
		return nil, types.WorkspaceScope{}, fmt.Errorf("invalid persisted transition outcome %q", record.Outcome)
	}
	if !validUTCTimestamp(record.CreatedAt) {
		return nil, types.WorkspaceScope{}, fmt.Errorf("invalid persisted transition timestamp")
	}
	record.CreatedAt = record.CreatedAt.UTC()
	return &record, scope, nil
}

func validateWorkspaceTransitionReceiptInsert(receipt WorkspaceTransitionReceiptInsert) ([]byte, []byte, error) {
	if !types.CanonicalUUID(receipt.RequestID) {
		return nil, nil, fmt.Errorf("localstore: invalid workspace transition request ID")
	}
	switch receipt.Action {
	case "stash", "restore", "discard":
	default:
		return nil, nil, fmt.Errorf("localstore: invalid workspace transition action %q", receipt.Action)
	}
	if !validWorkspaceTransitionDigest(receipt.RequestDigest) {
		return nil, nil, fmt.Errorf("localstore: invalid workspace transition request digest")
	}
	if err := receipt.Actor.ValidateHistorical(); err != nil {
		return nil, nil, fmt.Errorf("localstore: invalid workspace transition actor: %w", err)
	}
	actorJSON, err := projectstate.CanonicalJSON(receipt.Actor)
	if err != nil {
		return nil, nil, fmt.Errorf("localstore: encode workspace transition actor: %w", err)
	}
	resultJSON, err := canonicalTransitionResult(receipt.ResultJSON)
	if err != nil || !bytes.Equal(resultJSON, receipt.ResultJSON) {
		return nil, nil, fmt.Errorf("localstore: workspace transition result is not one canonical JSON value")
	}
	switch receipt.Outcome {
	case "clean", "conflicted":
	default:
		return nil, nil, fmt.Errorf("localstore: invalid workspace transition outcome %q", receipt.Outcome)
	}
	return actorJSON, bytes.Clone(resultJSON), nil
}

func decodeCanonicalTransitionActor(data []byte) (types.ActorEnvelope, error) {
	var actor types.ActorEnvelope
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&actor); err != nil {
		return types.ActorEnvelope{}, fmt.Errorf("invalid persisted transition actor JSON: %w", err)
	}
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err == nil {
			return types.ActorEnvelope{}, fmt.Errorf("invalid persisted transition actor JSON: multiple values")
		}
		return types.ActorEnvelope{}, fmt.Errorf("invalid persisted transition actor JSON: %w", err)
	}
	canonical, err := projectstate.CanonicalJSON(actor)
	if err != nil || !bytes.Equal(canonical, data) {
		return types.ActorEnvelope{}, fmt.Errorf("persisted transition actor JSON is not canonical")
	}
	if err := actor.ValidateHistorical(); err != nil {
		return types.ActorEnvelope{}, fmt.Errorf("invalid persisted transition actor: %w", err)
	}
	return actor, nil
}

func canonicalTransitionResult(data json.RawMessage) ([]byte, error) {
	canonical, err := projectstate.CanonicalJSON(json.RawMessage(bytes.Clone(data)))
	if err != nil {
		return nil, err
	}
	return canonical, nil
}

func validWorkspaceTransitionDigest(digest projectstate.Digest) bool {
	value := string(digest)
	if len(value) != len("sha256:")+64 || value[:len("sha256:")] != "sha256:" {
		return false
	}
	for _, char := range value[len("sha256:"):] {
		if !((char >= '0' && char <= '9') || (char >= 'a' && char <= 'f')) {
			return false
		}
	}
	return true
}
